# Generated by Django 3.1.1 on 2020-09-23 15:04

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='SEO описание')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Контент')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='ЧПУ ссылка')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.CharField(max_length=255, verbose_name='Произвольная ссылка')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Аттрибут title=')),
                ('target', models.CharField(blank=True, choices=[('_blank', '_blank'), ('_top', '_top'), ('_parent', '_parent')], max_length=10, null=True, verbose_name='Аттрибут target=')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='Отображать в меню')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
        migrations.CreateModel(
            name='HomeConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Интернет магазин', max_length=255, verbose_name='Название сайта')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Режим обслуживания')),
                ('home_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.page', verbose_name='Главная страница')),
            ],
            options={
                'verbose_name': 'Настройки',
            },
        ),
    ]
