# Generated by Django 3.1.1 on 2020-09-24 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200923_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='homeconfiguration',
            name='home_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_home', to='home.page', verbose_name='Главная страница'),
        ),
    ]
