# Generated by Django 3.1.1 on 2020-09-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200925_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Произвольная ссылка'),
        ),
    ]
