# Generated by Django 3.1.1 on 2020-10-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200925_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeconfiguration',
            name='contacts',
            field=models.TextField(blank=True, null=True, verbose_name='Контакты'),
        ),
    ]
