# Generated by Django 3.1.1 on 2020-09-23 19:04

from django.db import migrations, models
import django.db.models.deletion
import shop.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='SEO описание')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/category', verbose_name='Картинка')),
                ('active', models.BooleanField(default=True, verbose_name='Активная')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('short_text', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Контент')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.product_image_path, verbose_name='Картинка')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ярлык товара')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['order'],
            },
        ),
    ]
