# Generated by Django 3.1.1 on 2020-09-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_promo',
            field=models.BooleanField(default=False, verbose_name='Участвует в акции'),
        ),
    ]
