# Generated by Django 3.1.1 on 2020-09-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_is_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
