# Generated by Django 3.1.1 on 2020-09-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200925_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-order'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
