# Generated by Django 3.1.1 on 2020-09-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200925_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Порядок'),
        ),
    ]
