# Generated by Django 3.1.1 on 2020-10-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201002_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='Доставка'),
        ),
    ]
