# Generated by Django 3.1.2 on 2020-10-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201005_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Опция товара',
                'verbose_name_plural': 'Опции товара',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, to='shop.ProductOption', verbose_name='Опции'),
        ),
    ]
