# Generated by Django 3.1.2 on 2020-10-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20201006_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, to='shop.ProductOption', verbose_name='Опции'),
        ),
    ]
